@startuml
Class FamilyFeud
Class Categories
Class Team
Class TeamHandler
Class Timer
Class Questions
Class SQLite
Class TextUI
Class Round

FamilyFeud *-- Categories
FamilyFeud *-- TeamHandler
FamilyFeud *-- Timer
FamilyFeud *-- TextUI

Categories *-- Questions
TeamHandler *-- Team
SQLite <-- Categories : "Henter og gemmer"
SQLite <-- Questions : "Henter og gemmer"
Timer <-- Round
@enduml